# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Force a Qt platform to use. This sets the `QT_QPA_PLATFORM`
# environment variable and is useful to force using the XCB plugin when
# running QtWebEngine on Wayland.
# Type: String
#c.qt.force_platform = 'wayland'

config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

config.set('content.cookies.accept', 'all', 'devtools://*')

config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0', 'https://accounts.google.com/*')

# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36', 'https://*.slack.com/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow websites to show notifications.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.notifications.enabled', False, 'https://www.reddit.com')

# Height (in pixels or as percentage of the window) of the completion.
# Type: PercOrInt
c.completion.height = '25%'

c.statusbar.widgets = ['keypress', 'url', 'scroll', 'history', 'progress']

# Mouse button with which to close tabs.
# Type: String
# Valid values:
#   - right: Close tabs on right-click.
#   - middle: Close tabs on middle-click.
#   - none: Don't close tabs using the mouse.
c.tabs.close_mouse_button = 'none'

c.tabs.show = 'never'

# Open a new window for every tab.
# Type: Bool
c.tabs.tabs_are_windows = True

# Background color for webpages if unset (or empty to use the theme's
# color).
# Type: QtColor
c.colors.webpage.bg = '#111'

c.colors.webpage.preferred_color_scheme = 'dark'
c.colors.webpage.darkmode.enabled = True

# Bindings for normal mode
config.unbind('D')
config.unbind('d')
config.unbind('<Ctrl-h>')


config.unbind('u')
scripts = str(config.configdir) + '/userscripts/'
# turn these into guile scripts in the future
config.bind('uo','spawn --userscript ' + scripts + 'openr34')
config.bind('ua','spawn --userscript ' + scripts + 'artist')
config.bind('un','spawn --userscript ' + scripts + 'nhdownload')
config.bind('ur','spawn --userscript ' + scripts + 'r34d')

c.hints.selectors["every"] = ["*"]

config.bind(';a', 'hint every')

config.bind('K', 'scroll-px 0 -150')
config.bind('J', 'scroll-px 0 150')

config.bind(';v', 'hint links spawn -d mpv {hint-url}')
config.bind(',v', 'spawn -d mpv {url}')
config.bind(';V', 'hint links spawn -d mpv --ytdl-raw-options-add=cookies-from-browser=chromium:~/.local/share/qutebrowser/ {hint-url}')
config.bind(',V', 'spawn -d mpv --ytdl-raw-options-add=cookies-from-browser=chromium:~/.local/share/qutebrowser/ {url}')

config.bind('*', 'mode-enter set_mark')

