string = "#theme-tertiary"
comment = "#theme-soft"
keyword = { fg = "#theme-primary" , modifiers = ["bold"] }

"ui.background" = "#theme-background"
"ui.cursor" = {bg = "#theme-secondary"}
"ui.cursor.primary" = { fg = "#theme-background" ,bg = "#theme-tertiary" }
"ui.selection" = { bg = "#theme-soft-background" }
"ui.text" = "#theme-text"
"ui.popup" = {bg = "#theme-soft-background", fg = "#theme-primary" }
"ui.popup.info" = {bg = "#theme-soft-background", fg = "#theme-primary" }
"ui.help" = {bg = "#theme-soft-background", fg = "#theme-primary" }
"ui.statusline" = { bg = "#theme-soft-background" , fg = "#theme-primary" }
"ui.menu" = { bg = "#theme-soft-background", fg = "#theme-primary" }
"ui.menu.selected" = { bg = "#theme-background", fg = "#theme-secondary" }
